disabled_rules:
  - identifier_name
  - line_length
  - force_cast
  - force_try
  - large_tuple
  - todo
  - nesting
excluded:
  - Pods/
  - Podfile
  - Podfile.lock
  - Carthage/
  - Cartfile
  - Cartfile.resolved