# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CareButtons' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for CareButtons

  pod 'Firebase/Core'
  pod 'Firebase/Auth'
  pod 'Firebase/Firestore'
  pod 'Firebase/DynamicLinks'
  pod 'Firebase/Functions'
  
  target 'CareButtonsTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'CareButtonsUITests' do
    inherit! :search_paths
    # Pods for testing
  end
  
end

target 'CareButtonToday' do
    use_frameworks!
    
    pod 'Firebase/Core'
    pod 'Firebase/Auth'
    pod 'Firebase/Firestore'
    pod 'Firebase/DynamicLinks'
end
